### ISSUE TITLE
IndexOutOfBoundsException when processing blocks

### ISSUE THREAD

**Issue by kivanov82** [adridadou/eth-propeller-core#15]
Doesn't stop the block processing anymore but still something to have a look at:

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.adridadou.ethereum.rpc.EthereumRpc.toEventInfo(EthereumRpc.java:169)
	at org.adridadou.ethereum.rpc.EthereumRpc.lambda$toEventInfos$7(EthereumRpc.java:164)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.adridadou.ethereum.rpc.EthereumRpc.toEventInfos(EthereumRpc.java:164)
	at org.adridadou.ethereum.rpc.EthereumRpc.toReceipt(EthereumRpc.java:160)
	at org.adridadou.ethereum.rpc.EthereumRpc.lambda$toBlockInfo$6(EthereumRpc.java:143)

**Comment by adridadou** [comment]
fixed
